"""Writes bench/casos.mjs: the benchmark sweep, with the expected value of every case computed by the
independent Python references (bench/referencias.py) and stored as a SHA-256 of the printed value,
so that a 200,000-digit Fibonacci number does not have to live in a file.

x is the size shown on the plots: n or N for most workloads, the number of bits for isPrime.
Run: python bench/generar_casos.py
"""
import hashlib
import json
import sys
import time

import referencias as R

sys.set_int_max_str_digits(0)


def fib_matriz(n):
    """F(n) by 2x2 matrix powers: a third algorithm (Lean: fast doubling; referencias.fib: addition)."""
    def mul(a, b):
        return (a[0] * b[0] + a[1] * b[2], a[0] * b[1] + a[1] * b[3], a[2] * b[0] + a[3] * b[2], a[2] * b[1] + a[3] * b[3])
    r, m = (1, 0, 0, 1), (1, 1, 1, 0)
    while n:
        if n & 1:
            r = mul(r, m)
        m = mul(m, m)
        n >>= 1
    return str(r[1])


SWEEP = [("tunnell", [10**k + 3 for k in (3, 4, 5, 6)]),
         ("collatzRecord", [10**k for k in (3, 4, 5)]),
         ("primeCount", [10**k for k in (3, 4, 5, 6)]),
         ("mertens", [10**k for k in (3, 4, 5, 6)]),
         ("partitions", [100, 300, 1000, 3000]),
         ("fib", [10**k for k in (3, 4, 5, 6)]),
         ("fibBits", [10**k for k in (3, 4, 5, 6)]),
         ("partitionsBits", [100, 300, 1000, 3000]),
         ("isPrime", [(2**b - 1, b) for b in (31, 61, 89, 127, 521, 1279)]),
         ("lifePopulation", [10, 30, 100])]

casos = []
for w, args in SWEEP:
    for a in args:
        arg, x = a if isinstance(a, tuple) else (a, a)
        t = time.perf_counter()
        if w == "fibBits":
            v = str(int(fib_matriz(arg)).bit_length() - 1)
        elif w == "partitionsBits":
            v = str(int(R.partitions(arg)).bit_length() - 1)
        else:
            v = fib_matriz(arg) if w == "fib" and arg > 10**5 else getattr(R, w)(arg)
        if w == "fib" and arg <= 10**5:
            assert v == fib_matriz(arg), "the two Python Fibonacci algorithms disagree"
        casos.append({"w": w, "x": x, "arg": str(arg) if w == "isPrime" else arg,
                      "esperado": hashlib.sha256(v.encode()).hexdigest(), "muestra": v[:40], "digitos": len(v)})
        print(f"{w:15} x={x:<8} {v[:40]:40} ({time.perf_counter() - t:.1f} s)", flush=True)

import os

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "casos.mjs"), "w", encoding="utf-8", newline="\n") as h:
    h.write("// Generated by bench/generar_casos.py from the independent Python references -- do not edit.\n")
    h.write("// `esperado` is the SHA-256 of the value as printed (decimal).\n")
    h.write("export const CASOS = " + json.dumps(casos, indent=1) + ";\n")
print(len(casos), "cases")
